### ISSUE TITLE
META | Ember Interface Roadmap

### ISSUE THREAD

**Issue by Exelord** [ember-tooling/ember-hearth#44]
Hi,
Here is a quick list of features that we planned to add in https://github.com/ember-poland/ember-interface

## 1. Setup instruction
After the first run, you will see a model with small intro and required data like your default project folder, editor etc.

## 2. Projects and add-on list
On the left side, there should be a list of your ember projects, which are automatically added in the specified `projects folder`. There should be a quick possibility to open the directory and open in an editor.

## 3. Projects/Addon generator
You should be able to generate ember projects with just one click and passing its name. Optionally custom path.

## 4. Health status
After selecting the project it should be possible to view a list of all outdated packages with information about deprecations and security issues. On the projects list, there should be also a status icon which will indicate that status. it would be great to have also some native notifications.

## 5. Server and test runner
From the projects list, you should be able to click a (play) button to run a server or run the tests.

## 6. Community
You should be able to go to issues, PRs etc from project view, see some stats like collaborators, downloads counts and... Rating of the app based on users feedback. We should also allow developers to add comments to addons if needed.

## 7. Automatic migration guide
If there will be a new release of ember-cli you will see a proposal icon which will show you all the changes which are needed and migrate it manually or automatically.

## 8. Project Rebuild option
There should a button which will clean up all node_modules temps etc and install it from the ground.

Probably there was some plans and features. @poslinskinet if you know something more do not bother to add.

**Comment by PoslinskiNet** [comment]
# Feature
1. Not an easy one but would be an epic one to have an option to see a ERD diagram from the models of the project. Similar to this:

![ERD Diagram](https://i.stack.imgur.com/yQhmC.png)
